GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs 
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXI0IiwiaWQiOiI2MmE5Y2U2M2FkNmQyNWZkNzdjY2ZkNTkiLCJpYXQiOjE2NTUyOTU2MzZ9.zDVtzSUuLdmP5JXEh9C8gTrE3Hs1s82ZjfkPtz-ybyE

{
  "title": "Testing blog",
  "author": "Natalie",
  "url": "some.com",
  "likes": 8
}

###
POST http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
  "name": "Emily",
  "username": "User6",
  "password": "01239"
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
  "username": "User4",
  "password": "01234"
}

###
DELETE  http://localhost:3003/api/blogs/62a9e1e346e1a0c86b4f535f HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXI0IiwiaWQiOiI2MmE5Y2U2M2FkNmQyNWZkNzdjY2ZkNTkiLCJpYXQiOjE2NTUyOTU2MzZ9.zDVtzSUuLdmP5JXEh9C8gTrE3Hs1s82ZjfkPtz-ybyE
